package com.yggdrasil.model;

import java.io.Serializable;

public class NewickBean implements Serializable {
	
	private String newickFormat;	// UPGMA tree newick format generated by clustering

	/**
	 * 
	 */
	public NewickBean() {
		
	}

	/**
	 * @return the newickFormat
	 */
	public String getNewickFormat() {
		return this.newickFormat;
	}

	/**
	 * @param newickFormat the newickFormat to set
	 */
	public void setNewickFormat(String newickFormat) {
		this.newickFormat = newickFormat;
	}
	
	

}
